### ISSUE TITLE
GENERAL TALK

### ISSUE THREAD

**Issue by ezanchi** [Luke460/steering-wheel-master#3]
Just found that when you take the Preview window to another monitor with different resolution, it will still display at the original resolution it was first called in. It can't be manually resized as the content inside the window remains the same size and disappears.

Also, with my TV at 3840x2160 in 300% scale in can't see the bottom of the graph
![cant see the bottom](https://user-images.githubusercontent.com/22500633/91888477-45da6400-ec84-11ea-9598-ad9a9875c40e.png)

**Comment by Luke460** [comment]
Yes, I have noticed this problem. Unfortunately the automatic resize gave problems and I had to remove it. The simplest solution is a button for selecting the resolution.

**Comment by ezanchi** [comment]
Yeah, it's not something really important but just wanted to let you know.

Talking about something else, have you considered adding an Auto-updater?

What about uploading it to any forum where people can hopefully also suggest improvements?

**Comment by Luke460** [comment]
I can't fix this bug without causing major problems, it will remain a little known bug... however, you should get a notification from Windows that some windows may not fit the screen using the zoom, right?

**Comment by ezanchi** [comment]
> you should get a notification from Windows that some windows may not fit the screen using the zoom, right?

I don't get any notification from Windows at all. Its not really a problem that prevents anyone from using the main feature, but just a UIX hassle. Nothing to worry too much about.

**Comment by ezanchi** [comment]
> I updated the auto button in the version 2.4.3. It should suggest 9 in your case. (It's just a personal preference, let me know what is your favourite value!)

Just because I am too curious not to ask: what did change and how does it affect the LUT and the resulting Force Feedback?

**Comment by Luke460** [comment]
The lut generation is not affected at all, the only thing that change is the suggested value! :)

**Comment by Luke460** [comment]
Simply: it calculates the minimum aggregation value to have an increasing lut file, plus a coefficient due to the size of the input csv.
(It's still a "beta" feature, but it seems to work fine)

**Comment by Luke460** [comment]
Try the suggested aggregation (if you want) and tell me how the steering wheel feels

**Comment by ezanchi** [comment]
I have been trying the wheel and it feels nice, except for one thing:

When the car is going straight, and the wheel is centered, there is a vibration coming from the motors. Its like it doesn't have a deadzone in the middle so the motors are never fully off. Its only when I slightly tilt the wheel (2 o 3 deg max) to either side that the motors turn off. Of course, if I keep turning the wheel the motors come back to life, as expected.

Do you know what could be causing this? I suspect it might be because the LUT does not leave room for some deadzone...

**Comment by Luke460** [comment]
When this happens, you need to use a higher aggregation order. Tell me if 10 is not enough (in that case I need to add some values in the selector)

**Comment by Luke460** [comment]
I found that for aggregation orders 0, 1, 2 and 3 the generated lut for your steering wheel was not accurate in the middle (near 0)! Update to version 2.4.4

**Comment by ezanchi** [comment]
Use this CSV better. The other one was using sensitivity 100 in G HUB.
placeholder

**Comment by Luke460** [comment]
With the suggested value you should have a good compromise. Keep in mind that perfection is not achievable with a geared steering wheel. 


...but you can try to manually change some values in the csv:

0.000|0.000  ->  0.000|0.000 
0.001|0.150  ->  0.001|0.135  (-10%)
0.002|0.160  ->  0.002|0.147  (-8%)
0.001|0.165  ->  0.001|0.155  (-6%)
0.001|0.170  ->  0.001|0.163  (-4%)
0.001|0.175  ->  0.001|0.172  (-2%)
0.001|0.180  ->  0.001|0.178  (-1%)
0.001|0.185  ->  0.001|0.170
 . . . . . .

**Comment by Luke460** [comment]
Maybe in future I can add a new selector... Like: 

"Dead zone enhancement"

**Comment by ezanchi** [comment]
It feels good now. I just ran my CSV trough your tool and took the LUT out of it with SAO.

Question: Does the SAO use decimals internally? I feel that could help.

**Comment by Luke460** [comment]
No, I can't

**Comment by ezanchi** [comment]
Could you do something like:

(SAO.[0-99] - SAO.0) * NextValue

it would sort of use decimals that way right?

**Comment by Luke460** [comment]
It can't because it represents the number of aggregation iterations

**Comment by ezanchi** [comment]
Question: Does the AO (aggregate the previous and next AO values),
(ROUND(AO/2) previous values + ROUND(AO/2) next values) or
(just the next AO values)?

**Comment by Luke460** [comment]
No algebraic operation is performed on the OS

**Comment by ezanchi** [comment]
So what does the tool use AO for?

**Comment by Luke460** [comment]
`	public static ArrayList<Double> aggregate(ArrayList<Double> values, int aggregationOrder) {
		for(int state=0; state<aggregationOrder; state++) {
			values = aggregateInternal(values);
		}
		return values;
	}`

**Comment by Luke460** [comment]
It's just the number of the steps

**Comment by ezanchi** [comment]
And what is "values" when state=0?

**Comment by Luke460** [comment]
state = 0 is not less than 0 -> skip

**Comment by ezanchi** [comment]
So in that case it would only error correct the CSV right?

**Comment by ezanchi** [comment]
So "values" is a two dimensional array with index 0 being the WheelCheck step between 0 and Max Count, and index 1 being the real developed force?

**Comment by Luke460** [comment]
one-dimensional (you can re-execute it for each array)

**Comment by Luke460** [comment]
The new feature is live!

**Comment by ezanchi** [comment]
I will try it and ill tell you how it went 👍

**Comment by Luke460** [comment]
I couldn't make it adjustable for now

**Comment by ezanchi** [comment]
> The new feature is live! [v2.5]

Does it reflect in the Preview graph?

**Comment by Luke460** [comment]
Yes, but it is almost invisible or totally invisible due tu the low graph resolution. It's a minimal difference, but it can help a lot!

**Comment by ezanchi** [comment]
> Yes, but it's almost invisible or totally invisible due to the low graph resolution. It's a minimal difference, but it can help a lot!
> You can see it only by opening the lut file.

I tried the Deadzone and I still feel the wheel vibrating when neutral and car moving straight forward. Maybe somewhat weaker, but still there.

**Comment by Luke460** [comment]
Mmm, ok I'll try to change something

**Comment by ezanchi** [comment]
I should add I tried the LUT with SAO and DZ (Deadzone)

**Comment by Luke460** [comment]
I think the new option can't solve your problem. Minimal ffb granularity in the center is inevitable with a geared steering wheel.

**Comment by Luke460** [comment]
Added a slider for the selection of the enhanced dead zone (v2.6)

**Comment by ezanchi** [comment]
> Added a slider for the selection of the enhanced dead zone (v2.6.2)
> Also I reduced the size of the graph to 700px (Windows suggests to stay below 720 to avoid problems). Now it should fit in your 4k TV with the 300% zoom.

It only fits if I Fullscreen (square) the Window. Otherwise it won't fit because, I suspect, it leaves just a tiny gap between the display's top and the window, and that space is used at the bottom, and that renders the graph hidden behind the taskbar. Obviously, if I activate the "Hide Taskbar" option, then the graph's bottom becomes readable.

About the Deadzone Slider, I have to try it at 10 to see if it provides any improvement to the wheel when it is centered.

Ill let you know when I have some time.

**Comment by ezanchi** [comment]
I noticed that the first couple values of the graph are slanted to the right. But I'm not sure that would provide a deadzone so that the wheel's motors doesn't generate any force.

For it to be like that, I would say that the graph's green line should start more to the right (not at [0,0] but maybe at [5,0])

**Comment by ezanchi** [comment]
Okay I tried and the vibration are much more dampened, but still there.

Does what I teold you above make sense?

**Comment by Luke460** [comment]
> I noticed that the first couple values of the graph are slanted to the right. But I'm not sure that would provide a deadzone so that the wheel's motors doesn't generate any force.
> 
> For it to be like that, I would say that the graph's green line should start more to the right (not at [0,0] but maybe at [5,0])

I'm not sure I understand the question correctly, I guess you are wondering why the first values in the lut file ​​are not exactly 0, right?

**Comment by Luke460** [comment]
> Okay I tried and the vibration are much more dampened, but still there.
> 
> Does what I told you above make sense?

Nice, we are on the right way!

**Comment by Luke460** [comment]
Keep in mind that is impossible to eliminate the vibration at all. Even if you try to manually modify the lut... I tried :(

**Comment by Luke460** [comment]
> For it to be like that, I would say that the graph's green line should start more to the right (not at [0,0] but maybe at [5,0])

I get it! I tried and the vibration was enhanced! It seems that the vibration is directly proportional to the slope of the green line

**Comment by Luke460** [comment]
Ehy @ezanchi! I updated the Readme specifically for the G29. I suggest to you to try to not use aggregation, but only to enable "Dead zone correction only" and set "Dead zone enhancement" to 5 (or a similar value). 
...and the vibration will almost disappear!

**Comment by ezanchi** [comment]
> Ehy @ezanchi! I updated the Readme specifically for the G29. I suggest to you to try to not use aggregation, but only to enable "Dead zone correction only" and set "Dead zone enhancement" to 5 (or a similar value).
> ...and the vibration will almost disappear!

Hey! I will try those out and let you know 👍

**Comment by Luke460** [comment]
And... a brand new version is out: v2.9.0

**Comment by Luke460** [comment]
**My personal settings - Logitech G29**

The following are the settings I currently use on my personal steering wheel. My in-game FFB gain is set to 100%:

 - ***Aggregation order***: disabled (because I want to use a linear lut)
 - ***FFB Peak reduction***: 0 (personal preference, I like to feel every curb at 100%)
 - ***Dead zone enhancement***: 6.5 (this value depends on your wheel dead zone, but should be similar to this value)
 - ***Generate linear lut***: selected

**Comment by ezanchi** [comment]
> **My personal settings - Logitech G29**
> 
> The following are the settings I currently use on my personal steering wheel. My in-game FFB gain is set to 100%:
> 
> * _**Aggregation order**_: disabled (because I want to use a linear lut)
> * _**FFB Peak reduction**_: 0 (personal preference, I like to feel every curb at 100%)
> * _**Dead zone enhancement**_: 6.5 (this value depends on your wheel dead zone, but should be similar to this value)
> * _**Generate linear lut**_: selected

Why do you prefer linear LUT?

**Comment by Luke460** [comment]
Just personal preference.

I wanted to find out how good is a g29 out of the box, just correcting its biggest flaw: the huge dead zone.
And I have to say: pretty damn good! 
I wonder why Logitech has not solved this simple problem via software as I did with the linear lut.

**Comment by ezanchi** [comment]
Tried latest version and feels really nice!

My setting are AG8-PR0-DZ and for me its perfect. Obviously within the limitations of geared wheels, this improves the feeling a lot.

Good job so far!

**Comment by Luke460** [comment]
I'm really glad to know it worked for you after all! ✌ Domenica, 15 Novembre 2020, 01:12AM +01:00 da ezanchi  notifications@github.com :

**Comment by Luke460** [comment]
Hi @ezanchi ! Tonight, at 21:45 Europe Central Time, we are racing on Monza!
Our server is named 'NNA SimRacingClub' and the password is 'nna'. You can search the server simply by searching for 'nna ' (nna + space). 
You are welcome, of course!
We run on this server every Monday around 21:45

**Comment by ezanchi** [comment]
> Hi @ezanchi ! Tonight, at 21:45 Europe Central Time, we are racing on Monza!
> Our server is named 'NNA SimRacingClub' and the password is 'nna'. You can search the server simply by searching for 'nna ' (nna + space).
> You are welcome, of course!
> We run on this server every Monday around 21:45

Nice I will hop on at that time!

**Comment by Luke460** [comment]
Nice! No Problem, the pwd will change, but is not a problem

**Comment by CryptoTuner** [comment]
Hey I just wanted to tell you that what you are doing is absolutely incredible. I used your tool since the beginning more than 1 year ago, and you have made TONS of progress since. Thank you for doing this for free and open source. I believe nobody would be bothered if you added some Donation links somewhere in the tool and on the README file 😄
